version: '3.8'

services:
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/project
      - ./unit_tests:/project/unit_tests
    working_dir: /project
    command: [ "bash", "-c", "cd unit_tests && ./run_unit_tests.sh" ]
    environment:
      - CMAKE_GENERATOR=Ninja
