version: '3.8'
services:
  idf-test:
    build: .
    image: espressif/idf:v5.5.1-test
    volumes:
      - ../:/project
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /project
    environment:
      - DISPLAY=%DISPLAY%
    command: [ "bash", "/project/docker_tests/test_script.sh" ]
